### ISSUE TITLE
Updating controller-gen.yaml and zz_generated_controller.go

### ISSUE THREAD

**Issue by winglot** [Nexinto/kubernetes-icinga#10]
Hi,
i'm playing around with the code and trying to extend it's functionality but i'm stuck when it comes to updating `controller-gen.yaml` and `zz_generated_controller.go` files.

It seems that some tool/script is used to generate `zz_generated_controller.go` file from `controller-gen.yaml`. I cannot find it in this repo nor in any comments in source code.

Could you point me to the tool/script used for generating this controller file?

**Comment by iljaweis** [comment]
Hi,
the tool is at https://github.com/iljaweis/kube-controller-gen .

**Comment by winglot** [comment]
Thank, it worked!
